language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - thiago.cherubini@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: tPe1XaUZfu1TjxZMNS7A9TY14AAS1JnMhEO8L0olw9cobecKw9U7utdd9HycJmI/FQK1L/0kOKNa7JVl2gvTftl5YUiHAZ8noR6SXJ26zcIxSuoJy3kWZOfJZV4nazY+EoYFIad3ak5BRUUoATi3L7xgmm+sjcc1f1xei/DqXE/g/jgJDT092SPOB2OetdIwV4dM4HaWvaPI5i5OMuTxEWFuIHcY9W/xWLAjEh8nQ23c5wyIiglbhuQSguRY7YMzOE+1Ii13yS6wdK3oObyy1LTT6fa4t6y6hwuEHxbdkkzNFLxBXOOMhbpECLigt2vo9H9365TUgek6ryEzgpAjXj/knGrcopnPg1Y+Lv91reitHGw1+dQwiwFVtsxVbuQfT2unhdZuNq0VP22qbbJueI9UvPG/rTq5UfcLreffrWbfe+fLTjNf8KMFuOrmP99rQdax64raFc6uAxXmUa/jMasmdHFjZccbmlhbOpKztdwDbV+lNUclEejhMosaDZwPNeTMHVAmYsIKT7KyK5jAhxasOjJBOX0JGbIMR7Y7cg7VRy3Jr9gA4SjKAS6hIvxaJ26wS4KTtSbss8zPwDZQJ9O66GHp7E4oee0NHDq3bT+OmVL8PUcXTXSvnMC+W4V3NwAiKRXno5MPXhwyutb9hhbNQRkaySPh3JwMH7QvFlE=
  - secure: pGVdqjNjhavyR5INa1C5GB1RuCj4F4oQwYZB/HLdoZuHo/JgAd4sGmmWcx6fupkPsEPuMA3PPz4/ZzP8UDsgHabE+b5L9yBT3DqvLx0c/roaSadvIMAYthzRtPogYd+n00BrVdO8pA+D1KPDAHb3+VF0r1BXe1C9Q3341FxYXSIRR/wOzKJDZxhjgP3amhuGzewY4+oMUZ/WaEtEWq0rdFbgkyKEyoUmzqniSKSoeOppSH6Qhqt3vJfKjMemtvf1ETt1s/vWsYP5+k3UvDAy17wkIZWhtFkhwNcjftZLkki3FO9+yAjgiY/kBgq9p9j9ysBRu4r5D2/bwuYhxmTc/ctFV8YcVdzniO1LTgOcIx90ohe16eMxIQIpX8CEbh7DNRxrNTlob2S8d/wG0VPcuiDPxG7596vnNymKAX6t1D9bk0yXjH/9noLjGY/mLDqSpqzqjLf3zgdDE4IrBD1KyrfDNmJVkoIH/9zHnH9R1S9P5JmFTPar9Ar2Xcq9KjlzNvc7DdKpXvDw24YBZZUsM84X6dXpfwvkuA1FnD5itXYtfF3rikSxnsD+G+YWFfbj0v9+eNjupdIsz0LjjVvRQcwH+B58QWiQ130E4I9Lig8SXgKWouNW4aYrCKavRC476/KUM7upOK5u9oG12s/24RaNz3QJ0xYtkIM0NAUkC4k=
  - secure: vabCQe7Qi3Qq2MpMuWNfC2OnoAXOz1PgZaZ8idwBj/bJYa0qT/h1Tofx6x9KY0pKx2mTfA4qaO1qeHbWAiN8HismlxYaLPOHl6V2TSBf7hKfPrzrXs0dkSfUD+MwrhKjY3CFLWlK6TZqg08QEHYBrTtXVNEknEIIuHLVZVT2bgX/diQksKHo6NDWF72cGJF08odX7KUArnJcPYOBGAGjnFBRPKs1yNxLU141pVvJOMPXRP6sTbFDRTU6t1VTVFfT/7FbnzGwRet82rST/RKaaBgwTdOkrhFAThRFcsvvkmiqoHojqSOtETqi0lppKrWB0Kaul+nzugl3TKTWFiUFQL7sZJfK3BWJgrnPEbd024K7GYrUcr0YtanY/qqhiGqPg6pWooQwxntIur/jg5ExKWWGQ3KF3w09xcLiJTrCXBHgdiMLhu8mZ3dj91601KmScXQjBzEb3B/SWsQf2F50MKYvX8eH0TZn/Utjmq76Uja2/ENEfGp6ikdFLtERx9Kl+6faQbXPU/pD4wf7zbmslwRnwhOYOSXs6HDLLM2aJ0IxtUJeaHHXsbqWGqj9JPAiF4Z9Bj5kzT1M6+KcsySdk3uod8lgyY/WTAZA0FLCBJ9fJQL3FufE82tv1GpbDdKeXwviHWXsyD4OHeplHvuVDk2TfEy9hEGwxcKxIs2GMFs=
  - secure: QlCVpQcDb5guxMCqeBRbTREMZpwTWZMhSfIiAjOzvDS1WOA2oCbVVCjH1XR9hmfB0WxNn3mYuXv+knfVKtjsgNWptZqYMxYPbWhg4TtSbDm3PGHH5Q0okydDQGGmxFmP3bBUx6dLhlcQXQkMT58L24anVqiceDpxBvrMeLt5qmyEVCX8Ve1EKsPkimJqBrHkEE4dUTDtgjRnKbuDc+VOfwp1T5a0Kj2wYWRAIkACLjxYGjW2wljyHPQoUJ56emQL6fKeVElasDbzvlG+KuHcX11dT1yEHplKrXgxstWn0asDUr9Jp3soxet/zVLtyNRBO+JawILovwzNbVzIhuezI1s0NHwzT4b7uKSKP48uxTzUD5XNW/GPE1cP1yb4tX2XQkMEIhMCJtTAxLcgraGlkk7w0gZawSLcEX3JS2fWYeLQ72yVVzLiHVRosylBehjDAS1i5Qd+u2u9pwGttHutBPe5+77hWSGcaE3SGl9dsmOUsX/eKM6ROZ/Xkgc0O6qeFb6clbpXfsQp8RH1OEfpprSSyAZ8vASjXy0AUpNrtvcLzKZO8S/01OsWDDoaDkf/wF8AHkOeuTYbum4/LUaiyTnRD2tDjJPeEkW+syg8hlcCZ2bqcjCIenv4gqs+j0XQwQxBgAQYMsFsSxe9Ecn0Oa6EMGm98EdxokOIq8nvxg8=
  - secure: weLRzLo52krXyQS1wHCmsdZyszxAjQNO9pSByCfN64Fs38Um8oyYQZ5ajhshnjFN5xq3pXLf+Eb/+iuzLYRfYtl5HwA8ECOh7B3EkmiRGhP8Oxwj1MEXnbzyXBqyG24Ixfff51r3+huEUhjKzq2ax1s0luy42WpsJviSuN508CXObLL66xI3Ku+k5iQfSVV0Wu89Q7wMXZ4hFLkA8tY2Y3d2Yi1LgGU5LYXPb4zA8984qcVK5zTY3+9NB1EtmZyA3gFadU5PNs8MQO9JM2FI98NuIt43hipoAeCuW65oeVczG+ClJJlllW3tdsnsFUad+EkS+lO/FbqJBKo5+OZKc2nyhwtxtXwN2/yCiZaOOwftaljxkkezsJDCCLQwXIom9V54hBkR1RcZmRQEIOCyow0SB38J/CD3H201NbY+bsRrWlmizyRvArrvi+p2DjRmrUO40b2rK3MUh8WpU9IYDisnGmk4DTDTeRm8JTdbTSC8yZfkvRmgVZrOiKpPCbH8j64nt4ta8zcW64aChMJYrWTn8dkukr+civGGpjpAHHd48VcnpRKFm2IOODTyXGSOiDEEpsHoWl4jAF3vfk2EJzJDsezpk+m4ecMDkKQ5IXGdR8Agoie42Qj/h2M5zQoOwmkeDgWRUMgBi62GB3u5lAbVu84YaK075P4mp48kmI0=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=54.215.193.139
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
# sh travis_scripts/trigger_platform_tests.sh
