language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - thiago.cherubini@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: CSJhRLlxuv+fv8SnBehxDpLvU9NT/3/9+TXoXr9PuE5bxL02KfMHFPwGG0LT4PCAXP6dZc0f9Mahh6WRnJ4UjUJHZL0gkCe+HwhYcAb32+kj/0Nctnb170Q0xAf4xWemfZ32aJ7p7FiFYday2mx7HjrxheuLOCSk7qAjGJzurcvOsI1nKdooCQO9PxsG/lT1Jq2bJVYbiuC0N5Ja595PPErnPNBfG72ubyotEOwupVpHCzPFXY7K6EXyhysxyNRmpowknT1bcoOy72lBR2DBndMLs734vYwWAaI7Hi/SkB2FBbLwne/w8zWkXascOuzzi8Far4pJsi7JtFx9Uo1ZK7RTrLHIIvh1dtGQ4Kte2wbNecC/B3wxXlvimsS49uMEWBYmCIquEZTsn6X3oWrzlWgF0dQ9UXSWlIWq5ZxQ4dGS2vTih2DhZ2JjTOzdian5sVfJ1Lx1smAsPQUcEHzFoYKPeCunLPpwq3hEQdVGTGt4Ob9jduEp+kWKPzEIAaD22U6cSZBDm2OaCtwiJ1+Jn2DLQSqhlzyNHJD/qnzMeAW0aDvYCIzQIERjywSWLJAVuT+QhP0aThEbQvamkhMTBMEDCvhid7rkQYYW7aDQDzLT6wJ2X9lKM1mwZX+Q0IFvm7spGEg4HqHVQzb2+jx3sMDlwUI6cR5QEeCIA4XAwgE=
  - secure: nXrJ9DTbixW1pLeBXfsbftUcAnbTxtAPkxPFha4VRIJAIHVKrYPfR1JHn+Zitr8qy6aDhgvqrg1fuW+0Yl6Ar1+j7iD5k2QSomMyndEtq8/M1J8nturJZlbFXflFjq+pQsE5ofZ0Zr7aZWfaD9nmdcIuTC8MTELKuEh0yq2IdjNoF7wyD8gCsb7blqFVD9M3Tn/dbLRs4cuoe/os+6p665g5q8wpMiwhOcOsPFAk7GSlHOYkT57XnzsB30a5C3EY7dSOwdfb3AtN0eNy1K0PcFJP/0e8viHI2JVUDqAz2d7Y9obqowy+oBbhIWu6jqV6S6mQxLcXTtXrVzVODJpZ3XCBHJLb4W52WKsy8QZSy6haJfc9o8kzLRLTSTsTh4uk0DskeqlIhb6NGfl0hJ3gQ72WOy2s4XtU4z5q2LV7xscUUFE+wrB67qtcjO4yX2WX3ezOXA/lFutvdznIqtazurGPRnlk8M2N2cykevyBm+zf8VGo6zER8Bc/vSsA7jvZwC2JZSnpRFwGqBhd7KfT2ktPu4OpOsQ9Gj0hWqn1f5dOYCbp0oPcp5BFM5/iPfNEJkswm+dAdf2QNKOP8j/i9KhmA09wN/iVTGmNogkYJba52/nXLJ0Mbh5g2lL433KvWr5PQ+uOiey9P9k84w2srxGfLEmkHEQMP/2rklFTbyM=
  - secure: Mj2dyhD0cq4HOmgBbNS3HRzKJgeK+RCbhH2IsC3tsntNLeWPits+7vE029YWxRMBf/aCFq0ImyC16ER8p2bK68Sg7mRa+3IKw7yS5h/4pSrmduh5rG4v3Q/DI2MnyBtqaDztu/OaMWflez7T89yGANASBjy7FjRB1cIBtvL3G+UeIqTukp1DCwiFcBJ/9F8cjTdsPuA3sUVfTZcnJO/D+6auWEbbc3lpDhBfBSRo5lcigsMCzPnFkAvZNopq/i0jAHl8diKGRRT3MMGduvfLXhsdSlm+SaE5HLK3ZrrCZczO7sZZVVx0GMex3ElqPl7kX5onzW3i2BHVqJiXyrhAKX7Xkyf+4LdivI8NCnpytgyM4u/fX5fxfnnC6srCQgOZIgg4u16zh7gW4jhVMToQGc6rrMrbpD7CEUPDLtD1CcOIQoNxRTpSYSjg+bpz0assAX5MLF4+9Km6DtLeaIii7pZJQiIqNca57DDQnzxWgMrkFbNfBvqA1YZaqGG42vMrY8MF8nvK+2bTvbjBb4oFJ929OFwWla63A1vHu73WbYoPOO0slo/CNHaSFo5vSJIlxw+RmTcdlFeou3kpfIdtGCwLIZ+gaTDRGVjRkPX28DAPhReteLkY+Ex9FoIaupRqkPwwzLD8NGelrTYnYtYYqkp+asrXPqpDB6h/5VJDt6c=
  - secure: IexscbwSbX2C3afSQhDjN1PJJ0imgKdweypcnDAIPhWrKcHyEphsCbDaKbOj6oB7y9MBCS5u51FqqEHmJIIk5xdFM1jK1YEViX7Tv4b0KBEWs+xHmDdgSxjshOsfx0yAJB3yXIhYyzLnIPvZL1wgRzrY3UMUL/mYkAAzQJRpOh/06l+uHqIPIokX12sOTR9SlW7dEos5hVghnoOS47Nsou6GRzNWBL1t3NrkLC/JMi9Op9EXkSFxXuTEf03D8iOiTsEmsKqXT0xfhLpbTTLYwhnHGumaEPQ86KbHEcoRmg7D70pn1hSPW71f4owi9fS8inxyygdpEUS3jzYsgx1ALIBXR0/AksnBYom+Gad/zHq7bqjB9MAEAfBD4FQ43zOVhrbUZT3aL3Ms2FnJ4j7gI1eFzGLCwq1M1tqS9Nt+9e2vcaJOWR+7EtRxzbwYjN/bNkww1Xl7fsUQ4aKtcE89g16ZKq3S6cLzzs3TJOkKYdL74Y573ucxMKvh7D7WQYt3hqzCrpzRqccwgvshUKCR3CVpWpXO3nz7TvZ2Ct4c/NkMKrA0pqoVkWyZzZAqEX7KF3h+AWP0NnlIfnZWpUHJ+0CJ2Tuh5NRTccujzU4jshuIrI1+ekvTDUsfai4VZ7qsyYfqs0AGnUCzyhrJnfZ3K16xGcI0m3tm3HpHUCbRtKU=
  - secure: NTtviYd74SyWAvGzFKT7ekRL8uTocvb9jaCr2zZ6CxvI/v14kgZU00IKEJ6L0LWUVXFQwkryjoDzJ9plIB/QjOzAUF+HJjNb3B4FnuUQlT8bn9Yyvc+hc45x47Tu4wfTAG7UiOhYdqqZuPNOOx7xYxBEgkXozaImlUUxQDiH0zfc1Fr3uwkOw7fuCmJLhU6o/2heOM2i2jRbzq6ILGFNJWYzDhXezRoXP1yT2yUkTNhMcl9LCxtkR8ibiw8KS1jutTgSEeCKO9GmY1N85j1+L+fujE7a3Ct0SMno1LyjXyj6ql7a0mpdWJCrXSw4uguApu0+1rN+BFmuhpS5LfKYrY1jTIloOAXSW4fontEILACIDrX5NjDQ56FC9O+8MMn4FjxnLLGlg3AcxJT43QkrxxZqCGuXYUi1bCS/gp4m8PaOPEd/c2Hh1AJV1GcIo/BtohFRJ1QkOUiJZyo50qwG4FCRyrJTGRF5MzmGxRqIkISMSoRlq/6AkrroyABp6RFJjlDx3sLJeoK/+/zmGKYCRAiF8qCj255WH+gwu99qqwwwWJ4fLIbMg4Uyvr2/67Z1+mQv/3y/SvTnWfuBxp4zspTqAQPSSdyF607HeQeHYldpJrE2qutFFmxcvkXKm4mzX0PMy39Umij2/Kbl4D/GIKJFNBtdE57u9pU+wr3p/L0=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=54.215.193.139
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
# sh travis_scripts/trigger_platform_tests.sh
